name: Example Project Build (Automatic Conversion)
on: [pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clone https://github.com/QuantEcon/lecture-python-programming
        shell: bash -l {0}
        run: git clone https://github.com/QuantEcon/lecture-python-programming
      - name: Setup Anaconda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          auto-activate-base: true
          miniconda-version: 'latest'
          python-version: 3.7
          environment-file: lecture-python-programming/environment.yml
          activate-environment: qe-lectures
      - name: Install sphinxcontrib-tomyst
        shell: bash -l {0}
        run: python setup.py install
      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          pip install sphinx-book-theme myst-nb jupyter_client
      - name: Display Conda Environment Versions
        shell: bash -l {0}
        run: conda list
      - name: Display Pip Versions
        shell: bash -l {0}
        run: pip list
      - name: Build https://github.com/QuantEcon/lecture-python-programming
        shell: bash -l {0}
        run: |
          pwd
          cd lecture-python-programming
          git checkout sphinxcontrib-tomyst
          make myst
      - name: Build Myst Version
        shell: bash -l {0}
        run: |
          pwd
          cd lecture-python-programming/_build/myst/
          make html
      - name: Preview Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: 'lecture-python-programming/_build/myst/_build/html/'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Preview Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
